site_name: Backrooms FD-Class
repo_url: https://github.com/Chocolateater/FD-Class
edit_uri: 'https://github.com/Chocolateater/FD-Class/edit/master/docs/'
nav:
  - Home: 
    - Home: 'index.md'
    - Rules: 'Rules.md'
  - Levels: 
    - Level: 'Level_index.md'
    - Level 0-10: 
      - Level 0: 
        - Level 0 Main: 'Level_FD-0.md'
        - Level 0.1: 'Level_FD-0.1.md'
    #- Level 11-20:
    #- Level 21-30:
    - Level 31-40:
      - Level 32: 
        - Level 32 Main: 'Level_FD-32.md'
        - Level 32.5: 'Level_FD-32.5.md'
    - Level 41-50:
      - Level 45: 'Level_FD-45.md'
  - Entites:
    - Entity: 'Entity_index.md'
  - Objects:
    - Object: 'Object_index.md'
    # - 二代驱笑剂: '二代驱笑剂.md'
    
theme:
  name: material
  language: zh
  custom_dir : overrides
  icon:
    logo: fontawesome/solid/person-military-rifle
  features:
    - navigation.instant
    - navigation.tabs
    - content.action.edit
    - header.autohide
    - search.suggest
    - search.highlight
  plugins:
    - search
    - optimize
    - git-revision-date-localized:
      enable_creation_date: true
      type: date
      enable_creation_date: true
    - git-committers:
      repository: Chocolateater/FD-Class
      enabled: !ENV [CI]
  palette:
    primary: white
    scheme: 
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
extra:
  homepage: https://chocolateater.github.io/FD-Class/
    