site_name: My Docs
repo_url: https://github.com/Chocolateater/FD-Class
repo_name: Chocolateater/FD-Class
edit_uri: edit/master/docs/
theme:
  name: material
  features:
    - content.action.edit
  palette:
    primary: white
    scheme: 
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    