site_name: Backrooms FD-Class
repo_url: https://github.com/Chocolateater/FD-Class
edit_uri: 'https://github.com/Chocolateater/FD-Class/edit/master/docs/'
theme:
  name: material
  language: zh
  custom_dir : overrides
  icon:
    logo: fontawesome/solid/person-military-rifle
  features:
    - content.action.edit
    - header.autohide
    - search.suggest
    - search.highlight
  plugins:
    - search
    - optimize
  palette:
    primary: white
    scheme: 
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
extra:
  homepage: https://chocolateater.github.io/FD-Class/
    