site_name: Backrooms FD-Class
repo_url: https://github.com/Chocolateater/FD-Class
edit_uri: 'https://chocolateater.github.io/FD-Class/edit/?ref='
nav:
  - 主页 Home: 
    - Getting Started: 'index.md'
    - Rules: 'Rules.md'
    - 如何参与: 'Joinin.md'
    - 格式手册: 'Format.md'
    - 加入我们: 'Joinus.md'
  - 层级 Levels: 
    - Level: 'Levels/Level_index.md'
    - Level 0-10: 
      - Level 0: 
        - Level 0: 'Levels/Level_FD-0.md'
        - Level 0.1: 'Levels/Level_FD-0.1.md'
      - Level 1: 'Levels/Level_FD-1.md'
      - Level 5: 'Levels/Level_FD-5.md'
      - Level 8: 'Levels/Level_FD-8.md'
    - Level 11-20:
      - Level 11: 'Levels/Level_FD-11.md'
    #- Level 21-30:
    - Level 31-40:
      - Level 32: 
        - Level 32: 'Levels/Level_FD-32.md'
        - Level 32.5: 'Levels/Level_FD-32.5.md'
    - Level 41-50:
      - Level 45: 'Levels/Level_FD-45.md'
    - Other Levels: 
      - Level 218: 'Levels/Level_FD-218.md'
      - Level 418: 'Levels/Level_FD-418.md'
      - Level 2001: 'Levels/Level_FD-2001.md'
      - Level Ending: 'Levels/Level_FD_Ending.md'
      - Level Head To Head: 'Levels/Head_To_Head.md'
  - 实体 Entites:
    - Entity: 'Entities/Entity_index.md'
    - Entity 1: 'Entities/Entity_1_Loster.md'
    - Entity 5: 'Entities/Entity_5_Mom.md'
  - 物品 Objects:
    - Object: 'Objects/Object_index.md'
    - Coffee: 'Objects/Coffee.md'
    - Coffee_Milk: 'Objects/Coffee_Milk.md'
    # - 二代驱笑剂: '二代驱笑剂.md'
  - 组织 Organizations:
    - Organization: 'Organizations/Organization_index.md'
    - CCF: 'Organizations/CCF.md'
  - 现象 Phenomena:
    - Phenomena: 'Phenomena/Phenomena_index.md'
  - 更多 More…:
    - More: 'More/More_index.md'
    - 达尔文奖 Darwin: 'More/Darwin.md'
theme:
  name: material
  language: zh
  custom_dir : overrides
  icon:
    logo: fontawesome/solid/person-military-rifle
  features:
    - navigation.instant
    - navigation.tabs
    - content.action.edit
    # - header.autohide
    - search.suggest
    - search.highlight
    - announce.dismiss
  plugins:
    - search
    - optimize
    - git-revision-date-localized:
      enable_creation_date: true
      type: date
      enable_creation_date: true
    - git-committers:
      repository: Chocolateater/FD-Class
      enabled: !ENV [CI]
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra:
  homepage: https://chocolateater.github.io/FD-Class/

extra_javascript:
  # - javascripts/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # 上面 MathJax 下面 KaTeX
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
    
extra_css:
  - stylesheets/extra.css
